release 5.4.0.4

diff --git a/src/vendor/doctrine/dbal/.travis.yml b/src/vendor/doctrine/dbal/.travis.yml
--- a/src/vendor/doctrine/dbal/.travis.yml
+++ b/src/vendor/doctrine/dbal/.travis.yml
@@ -1,134 +1,393 @@
 language: php
+sudo: false
+dist: trusty
 
-php:
-  - 5.3
-  - 5.4
-  - 5.5
-  - 5.6
-  - hhvm
-  - hhvm-nightly
-
-env:
-  - DB=mysql
-  - DB=pgsql POSTGRESQL_VERSION=9.1
-  - DB=pgsql POSTGRESQL_VERSION=9.2
-  - DB=pgsql POSTGRESQL_VERSION=9.3
-  - DB=sqlite
-  - DB=mysqli
+cache:
+    directories:
+        - vendor
+        - $HOME/.composer/cache
 
 before_install:
-  - composer self-update
-
-install:
-  - composer update --prefer-source
+  - |
+    if [ "x$COVERAGE" != "xyes" ]; then
+      mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || true
+    fi
 
 before_script:
-  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS doctrine_tests;' -U postgres; fi"
-  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS doctrine_tests_tmp;' -U postgres; fi"
-  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database doctrine_tests;' -U postgres; fi"
-  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database doctrine_tests_tmp;' -U postgres; fi"
-  - sh -c "if [ '$DB' = 'pgsql' ]; then sudo service postgresql stop; sudo service postgresql start $POSTGRESQL_VERSION; fi"
-  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS doctrine_tests_tmp;create database IF NOT EXISTS doctrine_tests;'; fi"
-  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database IF NOT EXISTS doctrine_tests_tmp;create database IF NOT EXISTS doctrine_tests;'; fi"
+  - if [[ "$DB" == "mysql" || "$DB" == "mysqli" || "$DB" == *"mariadb"* ]]; then mysql < tests/travis/create-mysql-schema.sql; fi;
+  - |
+    if [ "x$COVERAGE" == "xyes" ] && [[ ! $(php -m | grep -si xdebug) ]]; then
+      echo "xdebug is required for coverage"
+      exit 1
+    fi
 
-script: ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
+install:
+  - rm composer.lock
+  - travis_retry composer -n update --prefer-dist
 
-matrix:
-  include:
-    - php: 5.3
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
-    - php: 5.4
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
-    - php: 5.5
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
-    - php: 5.6
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
-    - php: 7.0
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
-    - php: hhvm
-      env: DB=mariadb
-      addons:
-        mariadb: 5.5
+script:
+  - |
+    if [ "x$COVERAGE" == "xyes" ]; then
+       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml --coverage-clover clover.xml
+    else
+       ./vendor/bin/phpunit --configuration tests/travis/$DB.travis.xml
+    fi
 
-    - php: 5.3
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
-    - php: 5.4
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
-    - php: 5.5
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
-    - php: 5.6
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
-    - php: 7.0
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
-    - php: hhvm
-      env: DB=mariadb
-      addons:
-        mariadb: 10.0
+after_script:
+  - |
+    if [ "x$COVERAGE" == "xyes" ]; then
+      travis_retry wget https://github.com/scrutinizer-ci/ocular/releases/download/1.5.2/ocular.phar
+      travis_retry php ocular.phar code-coverage:upload --format=php-clover clover.xml
+    fi
 
-    - php: 5.3
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
-    - php: 5.4
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
-    - php: 5.5
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
-    - php: 5.6
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
-    - php: 7.0
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
-    - php: hhvm
-      env: DB=mariadb
-      addons:
-        mariadb: 10.1
+jobs:
   allow_failures:
-      - php: hhvm
-        env: DB=sqlite
-      - php: hhvm
-        env: DB=mysql
-      - php: hhvm
-        env: DB=mysqli
-      - php: hhvm
-        env: DB=mariadb
-      - php: hhvm-nightly
-  exclude:
-      - php: hhvm
-        env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
-      - php: hhvm
-        env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
-      - php: hhvm
-        env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
-      - php: hhvm-nightly
-        env: DB=pgsql POSTGRESQL_VERSION=9.1 # driver currently unsupported by HHVM
-      - php: hhvm-nightly
-        env: DB=pgsql POSTGRESQL_VERSION=9.2 # driver currently unsupported by HHVM
-      - php: hhvm-nightly
-        env: DB=pgsql POSTGRESQL_VERSION=9.3 # driver currently unsupported by HHVM
+    - php: nightly
+
+  include:
+    - stage: Test
+      php: 7.1
+      env: DB=mysql MYSQL_VERSION=8.0
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: 7.1
+      env: DB=mysqli MYSQL_VERSION=8.0
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: 7.1
+      env: DB=mariadb MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.1
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.1
+      env: DB=pgsql POSTGRESQL_VERSION=11.0
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-postgres-11.sh
+    - stage: Test
+      php: 7.1
+      env: DB=sqlite
+    - stage: Test
+      php: 7.1
+      env: DB=sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: 7.1
+      env: DB=pdo_sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-pdo_sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: 7.1
+      env: DB=ibm_db2
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-db2.sh
+        - bash ./tests/travis/install-db2-ibm_db2.sh
+    - stage: Test
+      php: 7.1
+      env: DB=sqlite DEPENDENCIES=low
+      install:
+        - travis_retry composer update --prefer-dist --prefer-lowest
+    - stage: Test
+      php: 7.2
+      env: DB=mysql COVERAGE=yes
+    - stage: Test
+      php: 7.2
+      env: DB=mysql MYSQL_VERSION=5.7 COVERAGE=yes
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-5.7.sh
+    - stage: Test
+      php: 7.2
+      env: DB=mysql MYSQL_VERSION=8.0 COVERAGE=yes
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: 7.2
+      env: DB=mysqli COVERAGE=yes
+    - stage: Test
+      php: 7.2
+      env: DB=mysqli MYSQL_VERSION=5.7 COVERAGE=yes
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-5.7.sh
+    - stage: Test
+      php: 7.2
+      env: DB=mysqli MYSQL_VERSION=8.0 COVERAGE=yes
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb MARIADB_VERSION=10.0 COVERAGE=yes
+      addons:
+        mariadb: 10.0
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb MARIADB_VERSION=10.1 COVERAGE=yes
+      addons:
+        mariadb: 10.1
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb MARIADB_VERSION=10.2 COVERAGE=yes
+      addons:
+        mariadb: 10.2
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb MARIADB_VERSION=10.3 COVERAGE=yes
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.0 COVERAGE=yes
+      addons:
+        mariadb: 10.0
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.1 COVERAGE=yes
+      addons:
+        mariadb: 10.1
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.2 COVERAGE=yes
+      addons:
+        mariadb: 10.2
+    - stage: Test
+      php: 7.2
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.3 COVERAGE=yes
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.2 COVERAGE=yes
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.2"
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.3 COVERAGE=yes
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.3"
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.4 COVERAGE=yes
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.4"
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.5 COVERAGE=yes
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.5"
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=9.6 COVERAGE=yes
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.6"
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=10.0 COVERAGE=yes
+      sudo: required
+      services:
+        - postgresql
+      addons:
+        postgresql: "9.6"
+      before_script:
+        - bash ./tests/travis/install-postgres-10.sh
+    - stage: Test
+      php: 7.2
+      env: DB=pgsql POSTGRESQL_VERSION=11.0 COVERAGE=yes
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-postgres-11.sh
+    - stage: Test
+      php: 7.2
+      env: DB=sqlite COVERAGE=yes
+    - stage: Test
+      php: 7.2
+      env: DB=sqlsrv COVERAGE=yes
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: 7.2
+      env: DB=pdo_sqlsrv COVERAGE=yes
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-pdo_sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: 7.2
+      env: DB=ibm_db2 COVERAGE=yes
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-db2.sh
+        - bash ./tests/travis/install-db2-ibm_db2.sh
+    - stage: Test
+      php: 7.3
+      env: DB=mysql MYSQL_VERSION=5.7
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-5.7.sh
+    - stage: Test
+      php: 7.3
+      env: DB=mysqli MYSQL_VERSION=5.7
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-5.7.sh
+    - stage: Test
+      php: 7.3
+      env: DB=mariadb MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.3
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: 7.3
+      env: DB=pgsql POSTGRESQL_VERSION=11.0
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-postgres-11.sh
+    - stage: Test
+      php: 7.3
+      env: DB=sqlite
+    - stage: Test
+      php: 7.3
+      env: DB=sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: 7.3
+      env: DB=pdo_sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-pdo_sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: nightly
+      env: DB=mysql MYSQL_VERSION=8.0
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: nightly
+      env: DB=mysqli MYSQL_VERSION=8.0
+      dist: xenial
+      sudo: required
+      before_script:
+        - bash ./tests/travis/install-mysql-8.0.sh
+    - stage: Test
+      php: nightly
+      env: DB=mariadb MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: nightly
+      env: DB=mariadb.mysqli MARIADB_VERSION=10.3
+      addons:
+        mariadb: 10.3
+    - stage: Test
+      php: nightly
+      env: DB=pgsql POSTGRESQL_VERSION=11.0
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-postgres-11.sh
+    - stage: Test
+      php: nightly
+      env: DB=sqlite
+    - stage: Test
+      php: nightly
+      env: DB=sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+    - stage: Test
+      php: nightly
+      env: DB=pdo_sqlsrv
+      sudo: required
+      services:
+        - docker
+      before_script:
+        - bash ./tests/travis/install-mssql-pdo_sqlsrv.sh
+        - bash ./tests/travis/install-mssql.sh
+
+    - stage: Test
+      if: type = cron
+      php: 7.2
+      env: DB=sqlite DEPENDENCIES=dev
+      install:
+        - composer config minimum-stability dev
+        - travis_retry composer update --prefer-dist
+
+    - stage: Code Quality
+      php: 7.2
+      env: DB=none STATIC_ANALYSIS
+      install: travis_retry composer install --prefer-dist
+      script: vendor/bin/phpstan analyse
+
+    - stage: Coding standard
+      php: 7.2
+      install: travis_retry composer install --prefer-dist
+      script:
+        - ./vendor/bin/phpcs
